{
  'error': True,
  'error_class': 'ActiveRecord::NoDatabaseError',
  'error_string': 'FATAL:  no pg_hba.conf entry for host "::1", user "msf", database "msf", SSL off\n',
  'error_backtrace': [
    "lib/active_record/connection_adapters/postgresql_adapter.rb:81:in `rescue in new_client'",
    "lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'",
    "lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'",
    "lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'",
    "lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'",
    "lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'",
    "lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'",
    "lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'",
    "lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'",
    "lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'",
    "lib/active_record/connection_adapters/abstract/connection_pool.rb:459:in `with_connection'",
    "lib/msf/core/db_manager/connection.rb:118:in `connection_established?'",
    "lib/metasploit/framework/data_service/proxy/core.rb:134:in `method_missing'",
    "lib/msf/core/rpc/v10/rpc_db.rb:1956:in `rpc_status'",
    "lib/msf/core/rpc/v10/service.rb:143:in `block in process'",
    "lib/timeout.rb:179:in `block in timeout'",
    "lib/timeout.rb:36:in `block in catch'",
    "lib/timeout.rb:36:in `catch'",
    "lib/timeout.rb:36:in `catch'",
    "lib/timeout.rb:188:in `timeout'",
    "lib/msf/core/rpc/v10/service.rb:143:in `process'",
    "lib/msf/core/rpc/v10/service.rb:81:in `on_request_uri'",
    "lib/msf/core/rpc/v10/service.rb:62:in `block in start'",
    "lib/rex/proto/http/handler/proc.rb:38:in `on_request'",
    "lib/rex/proto/http/server.rb:369:in `dispatch_request'",
    "lib/rex/proto/http/server.rb:303:in `on_client_data'",
    "lib/rex/proto/http/server.rb:162:in `block in start'",
    "lib/rex/io/stream_server.rb:42:in `on_client_data'",
    "lib/rex/io/stream_server.rb:185:in `block in monitor_clients'",
    "lib/rex/io/stream_server.rb:184:in `each'",
    "lib/rex/io/stream_server.rb:184:in `monitor_clients'",
    "lib/rex/io/stream_server.rb:64:in `block in start'",
    "lib/rex/thread_factory.rb:22:in `block in spawn'",
    "lib/msf/core/thread_manager.rb:105:in `block in spawn'",
    "lib/logging/diagnostic_context.rb:474:in `block in create_with_logging_context'"
  ],
  'error_message': 'FATAL:  no pg_hba.conf entry for host "::1", user "msf", database "msf", SSL off\n'
}
